
package com.soa.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ReservationService", targetNamespace = "http://gestionReservation.microservices.com/", wsdlLocation = "http://localhost:8888/ws/reservation?wsdl")
public class ReservationService_Service
    extends Service
{

    private static final URL RESERVATIONSERVICE_WSDL_LOCATION;
    private static final WebServiceException RESERVATIONSERVICE_EXCEPTION;
    private static final QName RESERVATIONSERVICE_QNAME = new QName("http://gestionReservation.microservices.com/", "ReservationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/ws/reservation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESERVATIONSERVICE_WSDL_LOCATION = url;
        RESERVATIONSERVICE_EXCEPTION = e;
    }

    public ReservationService_Service() {
        super(__getWsdlLocation(), RESERVATIONSERVICE_QNAME);
    }

    public ReservationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESERVATIONSERVICE_QNAME, features);
    }

    public ReservationService_Service(URL wsdlLocation) {
        super(wsdlLocation, RESERVATIONSERVICE_QNAME);
    }

    public ReservationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESERVATIONSERVICE_QNAME, features);
    }

    public ReservationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReservationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReservationService
     */
    @WebEndpoint(name = "ReservationServicePort")
    public ReservationService getReservationServicePort() {
        return super.getPort(new QName("http://gestionReservation.microservices.com/", "ReservationServicePort"), ReservationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReservationService
     */
    @WebEndpoint(name = "ReservationServicePort")
    public ReservationService getReservationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gestionReservation.microservices.com/", "ReservationServicePort"), ReservationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVATIONSERVICE_EXCEPTION!= null) {
            throw RESERVATIONSERVICE_EXCEPTION;
        }
        return RESERVATIONSERVICE_WSDL_LOCATION;
    }

}
