
package com.soa.client;

import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ReservationService", targetNamespace = "http://gestionReservation.microservices.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReservationService {


    /**
     * 
     * @param dateReservation
     * @param nom
     * @param nombrePersonnes
     * @param prenom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouterReservation", targetNamespace = "http://gestionReservation.microservices.com/", className = "com.soa.client.AjouterReservation")
    @ResponseWrapper(localName = "ajouterReservationResponse", targetNamespace = "http://gestionReservation.microservices.com/", className = "com.soa.client.AjouterReservationResponse")
    @Action(input = "http://gestionReservation.microservices.com/ReservationService/ajouterReservationRequest", output = "http://gestionReservation.microservices.com/ReservationService/ajouterReservationResponse")
    public String ajouterReservation(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "dateReservation", targetNamespace = "")
        XMLGregorianCalendar dateReservation,
        @WebParam(name = "nombrePersonnes", targetNamespace = "")
        int nombrePersonnes);

    /**
     * 
     * @return
     *     returns java.util.List<com.soa.client.Reservation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReservations", targetNamespace = "http://gestionReservation.microservices.com/", className = "com.soa.client.GetReservations")
    @ResponseWrapper(localName = "getReservationsResponse", targetNamespace = "http://gestionReservation.microservices.com/", className = "com.soa.client.GetReservationsResponse")
    @Action(input = "http://gestionReservation.microservices.com/ReservationService/getReservationsRequest", output = "http://gestionReservation.microservices.com/ReservationService/getReservationsResponse")
    public List<Reservation> getReservations();

    /**
     * 
     * @param nom
     * @param prenom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "annulerReservation", targetNamespace = "http://gestionReservation.microservices.com/", className = "com.soa.client.AnnulerReservation")
    @ResponseWrapper(localName = "annulerReservationResponse", targetNamespace = "http://gestionReservation.microservices.com/", className = "com.soa.client.AnnulerReservationResponse")
    @Action(input = "http://gestionReservation.microservices.com/ReservationService/annulerReservationRequest", output = "http://gestionReservation.microservices.com/ReservationService/annulerReservationResponse")
    public String annulerReservation(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom);

}
